# Generated by Django 3.2.4 on 2021-06-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choices_text',
            new_name='choice_text',
        ),
    ]
